image: mcr.microsoft.com/dotnet/core/sdk:3.1
pipelines:
  default:
    - step:
        name: Build
        script:
          - dotnet restore
          - dotnet build -p:DRBuildMode=coreonly
    - step:
        name: Test
        script:
          - dotnet test -p:DRBuildMode=coreonly
